operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  pre-app-run: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  pre-app-build: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  post-app-deploy: ./hooks/post-deploy.js
runtimeManifest:
  packages:
    workfront-ui-1:
      license: Apache-2.0
      actions:
        getdata:
          function: actions/getdata/index.js
          web: 'yes'
          runtime: nodejs:20
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
        onAemProcComplete:
          function: actions/onAemProcComplete/index.js
          web: 'yes'
          runtime: nodejs:20
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
            FIREFLY_SERVICES_ORG_ID: $FIREFLY_SERVICES_ORG_ID
            FIREFLY_SERVICES_CLIENT_ID: $FIREFLY_SERVICES_CLIENT_ID
            FIREFLY_SERVICES_USE_PASSED_AUTH: $FIREFLY_SERVICES__USE_PASSED_AUTH
            FIREFLY_SERVICES_CLIENT_SECRET: $FIREFLY_SERVICES_CLIENT_SECRET
            FIREFLY_SERVICES_SCOPES: $FIREFLY_SERVICES_SCOPES
            NEW_RELIC_LICENSE_KEY: $NEW_RELIC__LICENSE_KEY
            NEW_RELIC_LOG_LEVEL: $NEW_RELIC_LOG_LEVEL
            NEW_RELIC_ACCOUNT_ID: $NEW_RELIC_ACCOUNT_ID    
          annotations:
            require-adobe-auth: false
            final: true